apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-secret.fullname" . }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: poppin-vault
    kind: ClusterSecretStore
  {{- with .Values.target }}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
