apiVersion: apps/v1
kind: Deployment
metadata:
  name: poppin-backend-dev
  namespace: poppin
  labels:
    type: backend
    app: poppin-backend-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      app: poppin-backend-dev
  template:
    metadata:
      labels:
        type: backend
        app: poppin-backend-dev
    spec:
      containers:
        - name: spring
          image: poppinteam/backend-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 8080
              name: backend-port
          envFrom:
            - secretRef:
                name: poppin-backend

---
apiVersion: v1
kind: Service
metadata:
  name: poppin-backend-svc
  namespace: poppin
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /api/actuator/prometheus
    prometheus.io/port: "8080"
  labels:
    type: backend
    app: poppin-backend-dev
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      appProtocol: http
  selector:
    type: backend
    app: poppin-backend-dev
  type: ClusterIP