apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: review-service-dev
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/microservice/spring
    helm:
      valuesObject:
        replicaCount: 2
        image:
          repository: poppinteam/review-service
          pullPolicy: IfNotPresent
          tag: "2eadf70"
        service:
          type: ClusterIP
          port: 8080
        resources:
          limits:
            memory: 1Gi
        db:
          url: "jdbc:mysql://review-db-svc.review-service.svc.cluster.local:3306/review"
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: review-service
  
  syncPolicy: 
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true