apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: like-secrets
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/external-secret
    helm:
      valuesObject:
        target:
          name: "like-secrets"
        data:
          - secretKey: "MYSQL_ROOT_PASSWORD"
            remoteRef:
              key: "LIKE_MYSQL"
              property: "MYSQL_PASSWORD"
          - secretKey: "MYSQL_DATABASE"
            remoteRef:
              key: "LIKE_MYSQL"
              property: "MYSQL_DATABASE"
          - secretKey: "MYSQL_ROOT_USER"
            remoteRef:
              key: "LIKE_MYSQL"
              property: "MYSQL_USER"
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: like-service
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true