apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: location-secrets
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/external-secret
    helm:
      valuesObject:
        target:
          name: "location-secrets"
        data:
          - secretKey: "MONGODB_URI"
            remoteRef:
              key: "LOCATION_MONGODB"
              property: "URI"
          - secretKey: "MONGODB_USER"
            remoteRef:
              key: "LOCATION_MONGODB"
              property: "USERNAME"
          - secretKey: "MONGODB_PASSWORD"
            remoteRef:
              key: "LOCATION_MONGODB"
              property: "PASSWORD"
          - secretKey: "MONGODB_DATABASE"
            remoteRef:
              key: "LOCATION_MONGODB"
              property: "DATABASE"
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: location-service
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true