apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: review-secrets
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/external-secret
    helm:
      valuesObject:
        target:
          name: "review-secrets"
        data:
          - secretKey: "MYSQL_PASSWORD"
            remoteRef:
              key: "REVIEW_MYSQL"
              property: "MYSQL_PASSWORD"
          - secretKey: "MYSQL_DATABASE"
            remoteRef:
              key: "REVIEW_MYSQL"
              property: "MYSQL_DATABASE"
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: review-service
  
  syncPolicy: 
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true