apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poppin-location-mongodb
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/mongodb
    helm:
      valuesObject:
        auth:
          enabled: true
          rootPassword: rkcjseo123!
          username: poppin
          password: rkcjseo123!
          database: location
        
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: mongodb
  
  syncPolicy: 
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true