apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: like-redis
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/redis
    helm:
      valuesObject:
        architecture: standalone
        auth:
          enabled: true
          existingSecret: like-secrets
        master:
          resources:
            limits:
              memory: 4Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: like-service
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true