apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: like-db
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/mysql
    helm:
      valuesObject:
        service:
          type: ClusterIP
          port: 3306
        secretName: like-secrets
        initSchema: |
          CREATE TABLE location_like (
            like_count int NOT NULL,
            location_id bigint NOT NULL,
            locationlike_id bigint NOT NULL AUTO_INCREMENT,
            PRIMARY KEY (locationlike_id)
          ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

          CREATE TABLE user_like (
            location_id bigint NOT NULL,
            user_id bigint NOT NULL,
            userlike_id bigint NOT NULL AUTO_INCREMENT,
            PRIMARY KEY (userlike_id)
          ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: like-service
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true