apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: review-db
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/mysql
    helm:
      valuesObject:
        service:
          type: ClusterIP
          port: 3306
        secretName: review-secrets
        initSchema: |
          CREATE TABLE review (
            rating int DEFAULT NULL,
            created_at datetime(6) DEFAULT NULL,
            location_id bigint DEFAULT NULL,
            review_id bigint NOT NULL AUTO_INCREMENT,
            updated_at datetime(6) DEFAULT NULL,
            user_id bigint DEFAULT NULL,
            text varchar(255) DEFAULT NULL,
            title varchar(255) DEFAULT NULL,
            PRIMARY KEY (review_id)
          ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: review-service
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true