apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-db
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/pop-pin/infrastructure.git
    targetRevision: HEAD
    path: charts/mysql
    helm:
      valuesObject:
        service:
          type: ClusterIP
          port: 3306
        secretName: user-secrets
        initSchema: |
          CREATE TABLE user (
            user_id bigint NOT NULL AUTO_INCREMENT,
            email varchar(255) NOT NULL,
            role varchar(255) NOT NULL,
            username varchar(255) DEFAULT NULL,
            usernumber varchar(255) NOT NULL,
            PRIMARY KEY (user_id),
            UNIQUE KEY UK_ob8kqyqqgmefl0aco34akdtpe (email)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: user-service
  
  syncPolicy:
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true