apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-init
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
    initdb.sql: |
        {{ .Values.initSchema | nindent 8 }}